# fly.toml app configuration file generated for overcooked-cec-weathered-fire-3867 on 2025-09-01T22:22:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'overcooked-cec'
primary_region = 'bos'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-8x'
